version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      VERSION: "1.19.2"
      TYPE: "FORGE"
      FORGE_VERSION: "43.2.8"
      ONLINE_MODE: "FALSE"
      ENABLE_RCON: "true"
      MEMORY: "30G"
      VIEW_DISTANCE: "10"
      ALLOW_FLIGHT: "TRUE"
      DIFFICULTY: "normal"
      SEED:
      LEVEL_TYPE:
      MOTD: "Medvednavelosiped`s server"
      ENABLE_WHITELIST: "FALSE"
      SPAWN_PROTECTION: "50"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - /home/mnv/minecraft-data:/data
      - /home/mnv/minecraft-config/mods:/data/mods
      - /home/mnv/level:/data/world
      - /home/mnv/config:/data/config
  backup:
    image: offen/docker-volume-backup:v2
    environment:     
      AWS_ENDPOINT: "s3.timeweb.com"
      AWS_S3_BUCKET_NAME: ""
      AWS_ACCESS_KEY_ID: ""
      AWS_SECRET_ACCESS_KEY: ""
      #AWS_S3_PATH: "/world" 
      BACKUP_FILENAME: "backup-%Y-%m-%dT%H-%M-%S.tar.gz"
      BACKUP_PRUNING_PREFIX: "backup-"
      BACKUP_RETENTION_DAYS: "3"
      BACKUP_CRON_EXPRESSION: "0 12, 0 * * *"
    #env_file: ./backup.env
    volumes:
      - /home/mnv/level:/backup/level:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

