version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      VERSION: "1.19.2"
      TYPE: "FORGE"
      ONLINE_MODE: "FALSE"
      ENABLE_RCON: "true"
      MEMORY: "2G"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - /home/minecraft/minecraft-data:/data
      - /home/minecraft/minecraft-config/mods:/data/mods